"""add_hybrid_sequence_storage

Revision ID: 48677e88c9a5
Revises: d5aefab4ea84
Create Date: 2025-10-27 07:53:18.727220

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "48677e88c9a5"
down_revision: Union[str, Sequence[str], None] = "d5aefab4ea84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("sequences_name_key"), "sequences", type_="unique")
    op.create_unique_constraint(
        "uq_user_sequence_name", "sequences", ["user_id", "name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_sequence_name", "sequences", type_="unique")
    op.create_unique_constraint(
        op.f("sequences_name_key"),
        "sequences",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
