"""add hybrid sequence storage

Revision ID: d5aefab4ea84
Revises: 0dea406e2a94
Create Date: 2025-10-26 16:18:46.491158

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d5aefab4ea84"
down_revision: Union[str, Sequence[str], None] = "0dea406e2a94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequences", sa.Column("file_path", sa.String(length=500), nullable=True)
    )
    op.add_column("sequences", sa.Column("length", sa.Integer(), nullable=False))
    op.add_column("sequences", sa.Column("gc_content", sa.Float(), nullable=True))
    op.add_column("sequences", sa.Column("molecular_weight", sa.Float(), nullable=True))
    op.alter_column(
        "sequences", "sequence_data", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sequences", "sequence_data", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("sequences", "molecular_weight")
    op.drop_column("sequences", "gc_content")
    op.drop_column("sequences", "length")
    op.drop_column("sequences", "file_path")
    # ### end Alembic commands ###
