"""add sequence model

Revision ID: 26c7957fcd51
Revises: 8022e2afe3ea
Create Date: 2025-10-16 21:15:35.828723

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "26c7957fcd51"
down_revision: Union[str, Sequence[str], None] = "8022e2afe3ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sequences",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("sequence_data", sa.Text(), nullable=False),
        sa.Column(
            "sequence_type",
            sa.Enum("DNA", "RNA", "PROTEIN", name="sequencetype"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("sequence_data"),
    )
    op.create_index(op.f("ix_sequences_id"), "sequences", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sequences_id"), table_name="sequences")
    op.drop_table("sequences")
    # ### end Alembic commands ###
